sudo: false
language: python


env:
  global:
    secure: M1bzAX2MgqLN3Q2Zp8diK4vvnB3GSDMR9Y7Yiop4Go46Rk0sgYAlZfxSIrncTliYdSfcN+QcIhRk71sRDyQOZwtK80/xiFwe264PBMNkVDN4+BU+x+jLeK0g1uNXoWz+st8m+cD3ccLm2E6smQVe33WYsZ/QyvkKSKpJkGcxCLYvC+WMohkKTYs58yUJWnX2L46CjXVsUxhDWMLRrp64IQQkn4li0bJIu0DkfO+uyWfC1lczlEytMJg8u0aEMkRHZNY4Yr62BxZVATde3RfjvrpydhfzVulA9AMrcv517F29pFBm336uRIbZ2wL7KLV2HFB+tRu5wGVr2URYxClY5UQJnuw15o90/cnN2BUmhsV6hisc/uzdH+r0W49RsgQ05cu4/uCHO79fsRTKlTBxKFdpYls+4jdtJUY+SpEOm1hYSI7pTegUtlEGG5fmDRexXbqZrVLWqok+ZP0IJxIEBVRdIu4ThgdN+ilE+mndUaP7j/U04PjWmzXODlF2zlWq4BbnATBxtLZZGCsVTJWbmfQcKAV68xSVTbgdQDyPWK0OBfxXvjhplToDUAxfmSgzHIox/LlNGsj4Jtr/c7AwSjVQW2Z+MuXL5UbxdZT8ogVDERRc4xxxP4lCnpjygk93VLIMyuWhxYMVEOqKklmZJsWzpZIGakTYG3QYtT3HeYk=

python:
- 3.6
script: date ;  echo "Put secret in file and echo it backwards in case it is filtered: $SOMEVAR" > /tmp/junk.txt ; cat /tmp/junk.txt | rev
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
  user: traylenator
  password:
    secure: pASd1jq+1ZwLOGRW3IHlR9JRLajy4mC/cqE4EHu0uCEOioBtRt3ja1MCTQIcu9s+ynxvvb542+G6T+ciUfslczLMlx/1FMc/n0Zn6bEcMUl+IAykiEZ+bhYuTZin2mn2PoF3PBNdpJM5JQ9IhsoJmCnU1oijqeToKLV4AHEHRAgtK8Pj4++NV4lZFZ0CLEAjRurlc3zo/YrRWnrX8k/YPDJdxGrse29ZlqxvdLnASw2SvBh2XTiCrHhtMA7n/hhnx5g23pqwYXGvMCpt5kDjF7kEcsjuL6L45kYeOP1xQJxNwmAIs/5werXFj86Ep3948xWKpATJARQvS7gGtkUog2JLeekWWXnBHJAhRHmQG3zxz/j5ih+xmamDjWqGKR6FnWHtrIPm/4hZviRWGItyRZInnGFkNij7+6B4z4r5ECfbbyNhZECmnvldUzC6nyeDEHlhuCDjZQEY8V93jN5hCv7cEhBouX8XkPo3FopwK8QnxbduPfsBQpm0aAxCQ7WneAOh+zFvKpUVVZ4iLdMoXtfwYUolZ4Xh5UdkxOiPFutnW4/h+vEm69PpFLjQpy3gXTwf7BoEbHcCboHEJwgo9i9i2Kz6PGYThzqa6+mpEvgmoWtTs+ppqrJuGgfGGmSvzjHfQaJ+UWt1mmJhUAlck6Y3UErG3lzqvcpA08+Gf2U=

