sudo: false


env:
  global:
  - secure: Xt9HLHhSPtKnHK80a4GlLm/gJfPUaN9IjApTx7lo5b3MelTutpgA2+0Vf98XvOFCsg0XJOic4svlllhyi26gpo3C+m2cGyDvaLgpcBQ9N4kCbKkcQAwc8HVx8L5SQNqax/7BuNPZjTFLpjhhLLkjoyXgM/Jb7ZgDaTYHWxlcdh/KQYWOc2BhJB7AsbMf3jv5dEgMmPb+YtC7QmfB2mzn71MwfN61Jhk+NfkhZ1nFyniZZi/uE9aGPjHGItf4YplO3ztnMsf1CqpHJMlzQ8P1y8uBIkaNsD0oiHoMIfxTgj5TqraU+O7KfcX6GXJYimjsl0YQ+P0mosZL8272YBWkw8nd84oXgm1n/eUHMzoqkHb0eJHIotmUI2s8JOpWBAhTC5WGx9kvr8exVQFYJ4zqUBR0wAkpm09FKbbKgf8xdI0MnU7LxdUACtS/OmFgNf0NGnwwmWVtu0tlvuA+VCeLnLh+RXAabOBKmWo6K1lzv/g9EaqvKyND2vQwj4tQMU9e7uKE5XnhuGs/IiwnElpwt2y8xq2QjI7aWf4bdh4bLzB0a7T43x/+78N/Nx5Gzfm7G1Pnnf2xhvjfojg9Vp448tm7SQneXli5X/eCpsV36IbAdeNd176U6Nx/K2D0cNOdSD5OFPfY19V0M9YOdoxKi34/ufilXOyiBYqVXhJcwW4=

language: python
python:
- 3.6
script: date ;  echo "Secret $FOO" > /tmp/junk.txt ; cat /tmp/junk.txt | rev
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
  user: traylenator
  password:
    secure: pASd1jq+1ZwLOGRW3IHlR9JRLajy4mC/cqE4EHu0uCEOioBtRt3ja1MCTQIcu9s+ynxvvb542+G6T+ciUfslczLMlx/1FMc/n0Zn6bEcMUl+IAykiEZ+bhYuTZin2mn2PoF3PBNdpJM5JQ9IhsoJmCnU1oijqeToKLV4AHEHRAgtK8Pj4++NV4lZFZ0CLEAjRurlc3zo/YrRWnrX8k/YPDJdxGrse29ZlqxvdLnASw2SvBh2XTiCrHhtMA7n/hhnx5g23pqwYXGvMCpt5kDjF7kEcsjuL6L45kYeOP1xQJxNwmAIs/5werXFj86Ep3948xWKpATJARQvS7gGtkUog2JLeekWWXnBHJAhRHmQG3zxz/j5ih+xmamDjWqGKR6FnWHtrIPm/4hZviRWGItyRZInnGFkNij7+6B4z4r5ECfbbyNhZECmnvldUzC6nyeDEHlhuCDjZQEY8V93jN5hCv7cEhBouX8XkPo3FopwK8QnxbduPfsBQpm0aAxCQ7WneAOh+zFvKpUVVZ4iLdMoXtfwYUolZ4Xh5UdkxOiPFutnW4/h+vEm69PpFLjQpy3gXTwf7BoEbHcCboHEJwgo9i9i2Kz6PGYThzqa6+mpEvgmoWtTs+ppqrJuGgfGGmSvzjHfQaJ+UWt1mmJhUAlck6Y3UErG3lzqvcpA08+Gf2U=


